### ISSUE TITLE
版主，报这个错，是什么问题阿

### ISSUE THREAD

**Issue by yewei258** [ran-jit/tomcat-cluster-redis-session-manager#18]
redis.clients.jedis.exceptions.JedisException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:51)
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
	at tomcat.request.session.data.cache.impl.RedisDataCache$RedisCacheUtil.get(RedisDataCache.java:315)
	at tomcat.request.session.data.cache.impl.RedisDataCache.get(RedisDataCache.java:68)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:210)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:37)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2951)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2604)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:430)
	at tomcat.request.session.redis.SessionHandlerValve.invoke(SessionHandlerValve.java:37)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1156)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506)
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363)
	at redis.clients.util.Pool.getResource(Pool.java:49)

**Comment by ran-jit** [comment]
hi @yewei258,

Check your redis server. 

If redis server is stopped this exception ll be thrown.

**Comment by ran-jit** [comment]
Hi @yewei258,

Closing the issue. Please feel free to re-open or create new issue, if you're facing the issue with this session manager.

Thanks!
