### ISSUE TITLE
java.io.NotSerializableException: org.apache.catalina.session.StandardSessionFacade

### ISSUE THREAD

**Issue by lizhen1770** [ran-jit/tomcat-cluster-redis-session-manager#21]
Hi,My project use springboot2.0.6、tomcat9.0.10、jdk1.8 and use spring security to control login.I can open the login view,but login failed and log say：
tomcat.request.session.redis.SessionManager.save Error occured while saving the session object in data cache..
 java.io.NotSerializableException: org.apache.catalina.session.StandardSessionFacade
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at java.util.HashMap.internalWriteEntries(HashMap.java:1790)
        at java.util.HashMap.writeObject(HashMap.java:1363)
        at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeUnshared(ObjectOutputStream.java:415)
        at tomcat.request.session.SerializationUtil.getSessionAttributesHashCode(SerializationUtil.java:60)
        at tomcat.request.session.redis.SessionManager.save(SessionManager.java:299)
        at tomcat.request.session.redis.SessionManager.afterRequest(SessionManager.java:333)
        at tomcat.request.session.redis.SessionHandlerValve.invoke(SessionHandlerValve.java:39)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:764)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1388)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

Thanks.

**Comment by ran-jit** [comment]
Hi @lizhen1770,

This session manager accepts only the Serializable objects. If you try to set session with Non Serializable Object value you will get this exception.

<img width="664" alt="screenshot 2018-11-30 at 2 03 37 am" src="https://user-images.githubusercontent.com/8708711/49250160-2aee1680-f444-11e8-854b-3bd6ca0dd863.png">


**Resolution:** Please implement the classes with Serializable interface.

<img width="703" alt="screenshot 2018-11-30 at 2 12 24 am" src="https://user-images.githubusercontent.com/8708711/49251068-90db9d80-f446-11e8-9802-5410224b72da.png">

**Reason:** We're converting an object (value) into a stream of bytes and storing it into redis data cache. So please implement the classes with Serializable and add the "serialVersionUID" (During serialization, java runtime associates a version number with each serializable classes. This number called serialVersionUID, which is used during deserialization to verify the serialized object).

Hope it helps!!

Thanks!

**Comment by ran-jit** [comment]
I've added a note in [Readme file](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/blob/master/README.md).
