### ISSUE TITLE
5 Seconds retry after connection lost

### ISSUE THREAD

**Issue by mmack** [ran-jit/tomcat-cluster-redis-session-manager#33]
Hey, 

it the 5 Seconds timeout from this error message configurable? Background is that i've confiured my sentinels to switch over master after one second, so this could be much shorter so people won't recognize the outage...

```
12-Apr-2019 10:06:11.885 SEVERE [MasterListener-intranet-[intranet-redis-ha-announce-4:26379]] redis.clients.jedis.JedisSentinelPool$MasterListener.run Lost connection to Sentinel at intranet-redis-ha-announce-4:26379. Sleeping 5000ms and retrying.
 redis.clients.jedis.exceptions.JedisConnectionException: java.net.ConnectException: Connection refused (Connection refused)
	at redis.clients.jedis.Connection.connect(Connection.java:207)
	at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:93)
	at redis.clients.jedis.Connection.setTimeoutInfinite(Connection.java:94)
	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2678)
	at redis.clients.jedis.JedisSentinelPool$MasterListener.run(JedisSentinelPool.java:291)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at redis.clients.jedis.Connection.connect(Connection.java:184)
	... 4 more
```

**Comment by ran-jit** [comment]
Hi @mmack,

This retry timing is internal to Jedis client and it's not configurable.

In the sentinel mode, the Jedis client will retry until a new Master node is elected by the Redis server. Also, if the Jedis client throws a connection exception, this session manager will retry 3 times every 2 seconds until the client receives a connection. So the probability of data loss is very less.

Thanks!

**Comment by mmack** [comment]
It says "Sleeping 5000ms and retrying." and not 2 Seconds though... :)

**Comment by ran-jit** [comment]
yes. 5000ms is internal to Jedis client.

If the current sentinel master node is not accessible/down, the Jedis client internally retries every 5000ms. If the runtime error in this process occurs, this session manager will retry 3 times every 2 seconds until the client gets the connection.

I hope it's clear now.

**Comment by ran-jit** [comment]
FYI: https://github.com/ran-jit/tomcat-cluster-redis-session-manager/issues/29

**Comment by ran-jit** [comment]
Closing this issue. Please feel-free to reopen this issue/create new issue, if you require additional details in future.
