### ISSUE TITLE
请问启动报这个错是什么原因呢?

### ISSUE THREAD

**Issue by it-wwh** [ran-jit/tomcat-cluster-redis-session-manager#35]
四月 23, 2019 2:57:35 下午 org.apache.coyote.http11.AbstractHttp11Processor process
严重: Error processing request
java.lang.NullPointerException
	at com.orangefunction.tomcat.redissessions.RedisSessionHandlerValve.invoke(RedisSessionHandlerValve.java:28)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2575)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2564)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ran-jit** [comment]
Hey @it-wwh,

Which version of session manager you're using?

**Comment by it-wwh** [comment]
哦,谢谢已经解决了,原因是我把那段配置写到了server.xml中了,实际应该放在context.xml中

**Comment by ran-jit** [comment]
Please reply in English. Thanks!

**Comment by it-wwh** [comment]
The problem has been solved. Thank you.

**Comment by ran-jit** [comment]
Thanks, @it-wwh for the update.
