### ISSUE TITLE
 Could not initialize class tomcat.request.session.data.cache.DataCacheFactory

### ISSUE THREAD

**Issue by zhangzemin2016** [ran-jit/tomcat-cluster-redis-session-manager#37]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class tomcat.request.session.data.cache.DataCacheFactory
        at tomcat.request.session.redis.SessionManager.initialize(SessionManager.java:206)
        at tomcat.request.session.redis.SessionManager.startInternal(SessionManager.java:80)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 12 more

**Comment by zhangzemin2016** [comment]
下载的zip包，复制里面的jar包到tomcat的lib下，将redis-data-cache.properties复制到tomcat/conf/目录下，修改了catalina.bat添加了catalina.base为tomcat路径，set redis-data-cache.properties cluster=true，tomcat version 7.0.93,redis version 5.0.3 used password

**Comment by zhangzemin2016** [comment]
sorry,just a problem for log4j
