### ISSUE TITLE
SingleSignOn valve support

### ISSUE THREAD

**Issue by martin-ocasek** [ran-jit/tomcat-cluster-redis-session-manager#51]
Hi, would it be possible to add support for [SingleSignOn ](https://tomcat.apache.org/tomcat-9.0-doc/api/org/apache/catalina/authenticator/SingleSignOn.html)valve using redis as session storage cache ? 
We would like  to be able to use tomcats SSO functionality while using redis as SSO session storage.

**Comment by ran-jit** [comment]
Hi @martin-ocasek,

I added Single Sign-On (SSO) support changes. But I don't have the test environment ready. So Please give me some time I will test and keep you posted.

**Comment by ran-jit** [comment]
Hey @martin-ocasek,

I have merged the [changes](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/pull/52) and created a [pre-release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.5) (version: 3.0.5)

To enable SSO, please use the below two lines in tomcat/conf/context.xml

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<Valve className="tomcat.request.session.redis.SingleSignOnValve" />`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<Manager className="tomcat.request.session.redis.SessionManager" />`

I hope this helps. Thanks!

**Comment by martin-ocasek** [comment]
Hi, thanks for adding the feature. However im getting an exception when starting in Tomcat 9.0.30

`	Caused by: org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([STARTING]) for component [SingleSignOnValve[StandardEngine[Catalina].StandardHost[localhost].StandardContext[/docs]]] in state [STARTING]
`

Its just a clean Tomcat download with included webapps.

`31-Mar-2020 12:38:45.951 SEVERE [main] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory [C:\Dev\App_servers\apache-tomcat-9.0.30-windows-x64\apache-tomcat-9.0.30\webapps\docs]
	java.lang.IllegalStateException: Error starting child
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)
		at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1867)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
		at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
	Caused by: org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([STARTING]) for component [SingleSignOnValve[StandardEngine[Catalina].StandardHost[localhost].StandardContext[/docs]]] in state [STARTING]
		at org.apache.catalina.util.LifecycleBase.invalidTransition(LifecycleBase.java:430)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:416)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.valves.ValveBase.startInternal(ValveBase.java:165)
		at org.apache.catalina.authenticator.SingleSignOn.startInternal(SingleSignOn.java:610)
		at tomcat.request.session.redis.SingleSignOnValve.startInternal(SingleSignOnValve.java:37)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:176)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5063)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
		... 37 more

`

**Comment by ran-jit** [comment]
Hi! Can you please help me set up the SSO in tomcat? Thanks!

**Comment by martin-ocasek** [comment]
For default tomcat SSO you need to use 
`<Valve className="org.apache.catalina.authenticator.SingleSignOn" />`
inside of conf\server.xml. Then if you authenticate using one of the default apps for example, you should get SSO session assigned, you can change its name by specifying [org.apache.catalina.authenticator. Constants.SSO_SESSION_COOKIE_NAME](http://www.medcordex.eu:8080/docs/config/systemprops.html#Sessions) property inside conf\catalina.properties.

**Comment by ran-jit** [comment]
Hey @martin-ocasek,

I've updated the changes in 3.0.5 [release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.5). Please, update the new session manager in your tomcat and check the same.

To enable SSO, please use the below config

1. tomcat/conf/context.xml
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<Valve className="tomcat.request.session.redis. SessionHandlerValve" />`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<Manager className="tomcat.request.session.redis.SessionManager" />`

2. tomcat/conf/server.xml
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`<Valve className="tomcat.request.session.redis. SingleSignOnValve" />` instead of `<Valve className="org.apache.catalina.authenticator.SingleSignOn" />`

I hope this helps. Thanks!

**Comment by martin-ocasek** [comment]
Hey, tomcat now starts properly but im still having some issues. When i log in and the SSOEntry is being stored in redis cache i get an exception related to object serialization:
```

java.io.NotActiveException: not in call to writeObject
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:436)
	at tomcat.request.session.model.SingleSignOnEntry.writeObjectData(SingleSignOnEntry.java:81)
	at tomcat.request.session.util.SerializationUtil.serializeSingleSignOnEntry(SerializationUtil.java:86)
	at tomcat.request.session.redis.SessionManager.setSingleSignOnEntry(SessionManager.java:354)
	at tomcat.request.session.redis.SingleSignOnValve.register(SingleSignOnValve.java:181)
	at org.apache.catalina.authenticator.AuthenticatorBase.register(AuthenticatorBase.java:1075)
	at org.apache.catalina.authenticator.AuthenticatorBase.register(AuthenticatorBase.java:983)
	at org.apache.catalina.authenticator.BasicAuthenticator.doAuthenticate(BasicAuthenticator.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:572)
	at tomcat.request.session.redis.SessionHandlerValve.invoke(SessionHandlerValve.java:29)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at tomcat.request.session.redis.SingleSignOnValve.invoke(SingleSignOnValve.java:88)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ran-jit** [comment]
Hey @martin-ocasek!

Fixed the issue and updated the changes in the [3.0.5 release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.5). Please, update the new session manager in your tomcat and check the same.

Thanks!

**Comment by martin-ocasek** [comment]
Hi, i did some more testing and found some small issues, it looks like sessionKeys attribute of SingleSignOnEntry is not being serialized. But it seems like adding 
` outputStream.writeObject(this.sessionKeys);`
into SingleSignOnEntry.writeObjectData, and
`this.sessionKeys.putAll((ConcurrentMap<SingleSignOnSessionKey, SingleSignOnSessionKey>) inputStream.readObject());`
into SingleSignOnEntry.readObjectData might fix that issue.

Also i feel like in SessionManager.getSingleSignOnEntry, there should be a nullcheck for data returned from dataCache. currently if client send SSO ID of session that is not found in redis the applications fails with NPE.

**Comment by ran-jit** [comment]
Hey @martin-ocasek!

Updated the changes in the 3.0.5 release. Please, update the new session manager in your tomcat and check the same.

Thanks!

**Comment by martin-ocasek** [comment]
Hey, we have been using the new version in our development environment for a while and found a few things.

1. when session gets invalidated a warning is logged `...tomcat.request.session.redis.SingleSignOnValve.expire singleSignOn.sessionExpire.hostNotFound...` (https://github.com/ran-jit/tomcat-cluster-redis-session-manager/blob/80acc01418a038fbe047a4d6d4f01bcae3ff5e71/src/main/java/tomcat/request/session/redis/SingleSignOnValve.java#L228) it seems that host Container cannot be retrieved from Context object. Default tomcat implementation uses Engine object instead of Context (https://github.com/apache/tomcat/blob/master/java/org/apache/catalina/authenticator/SingleSignOn.java#L436) through which the host Container can be successfully retrieved.

2. Would it be possible to add some kind of SSO session timeout through configuration ? Possibly in similar way as for normal sessions. Currently if the session is not properly invalidated/destroyed it stays in redis pretty much forever.

Thank you.

**Comment by ran-jit** [comment]
Hey @martin-ocasek!

Updated the changes in the [3.0.5.1 release](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/3.0.5.1). Please, update the new session manager in your tomcat and check the same.

> #- single-sign-on session timeout. (default value: 0 ms (-no expiry))
> redis.sso.timeout=0

Thanks!

**Comment by ran-jit** [comment]
I'm closing this. If you require additional details in the future, please feel free to reopen this/create a new issue.

Thanks!
