### ISSUE TITLE
java.lang.NoSuchMethodError: tomcat.request.session.redis.SessionManager.getContext()Lorg/apache/catalina/Context;

### ISSUE THREAD

**Issue by alex-francis-w** [ran-jit/tomcat-cluster-redis-session-manager#7]
there has an error in the class of SessionManager in the line of 129: getContext()

**Comment by ran-jit** [comment]
@alex-francis-w,

Which tomcat version you're using ?

**Comment by alex-francis-w** [comment]
I have knew reason of the error ,
I should use the 1.0 version with tomcat7.
but i have another question about the lifecycle of session in redis,
In the version of 2.0, when the tomcat shutdown, the manager of session will destroy sessions in redis, but in the version of 1.0 ,the session will not be destroyed, so how do i do that the 1.0 will destroy the session in redis when the server shutdown

**Comment by ran-jit** [comment]
The session values are removed from redis based on the expiry time. We're not deleting the session value from redis when the server shutdown in both implementation (1.x & 2.x).

I tried to reproduce the reported issue (NoSuchMethodError) in my local, working fine as expected.

Tested version:
1. apache-tomcat-7.0.47
2. apache-tomcat-7.0.82
3. apache-tomcat-8.5.20

Based on the tomcat/conf/web.xml --> <session-config> value, the session objects expired/removed from redis.

**Comment by alex-francis-w** [comment]
I have set session-timeout value 30 in tomcat/conf/web.xml
but when i start the tomcat , there is a report that 'Oct 20, 2017 10:29:54 AM com.r.tomcat.session.management.RequestSessionManager startInternal
INFO: The sessions will expire after 900 seconds'
It makes me confused, what's mean about that?

**Comment by ran-jit** [comment]
@alex-francis-w,

I've identified and fixed the issue.

I request you to kindly upgrade your session manager from 1.x to [2.0.1](https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/2.0.1).

#### Migration procedure from 1.x to 2.x
 * Replace redis data-cache properties in tomcat/conf directory.
 * Update the below lines in tomcat/conf/context.xml file.
        <Valve className="tomcat.request.session.redis.SessionHandlerValve" />
        <Manager className="tomcat.request.session.redis.SessionManager" />

Release 2.0.1: https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/tag/2.0.1

Thanks!

**Comment by alex-francis-w** [comment]
Another issue come up : 
When I startup tomcat ,everything is ok,
then i keep accessing the tomcat , one of these access come up an error : 
SEVERE: Error occured while de-serializing the session object..
java.lang.ClassNotFoundException: org.springframework.security.web.savedrequest.DefaultSavedRequest
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.catalina.util.CustomObjectInputStream.resolveClass(CustomObjectInputStream.java:151)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at org.apache.catalina.session.StandardSession.readObject(StandardSession.java:1609)
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1075)
	at tomcat.request.session.Session.readObjectData(Session.java:130)
	at tomcat.request.session.SerializationUtil.deserializeSessionData(SerializationUtil.java:109)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:226)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:37)
But the server is not effected, it still work properly.

**Comment by ran-jit** [comment]
@alex-francis-w,

**java.lang.ClassNotFoundException: org.springframework.security.web.savedrequest.DefaultSavedRequest**

ClassNotFoundException is from Spring framework. I think you've missed some of your project dependency (spring-security-web.jar). Please check.

**Comment by ran-jit** [comment]
Hi @alex-francis-w,

Any update ..?

Please let me know if you're facing issues.

Thanks,
\ Ranjith

**Comment by alex-francis-w** [comment]
uh, Now it's runing porperly.

At last, I want to say: Thank you for helping me resolve these issues.

**Comment by ran-jit** [comment]
Thanks @alex-francis-w !!

**Comment by ced1967** [comment]
Hi,

I'm using Tomcat8 and jedis-2.9.0.jar. When the session is restored I always get an error like this:

SEVERE: Error occured while de-serializing the session object..
java.lang.ClassCastException: tomcat.request.session.SessionMetadata cannot be cast to tomcat.request.session.SessionMetadata
	at tomcat.request.session.SerializationUtil.deserializeSessionData(SerializationUtil.java:107)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:226)
	at tomcat.request.session.redis.SessionManager.findSession(SessionManager.java:1)
	at org.apache.catalina.connector.Request.doGetSession(Request.java:2868)
	at org.apache.catalina.connector.Request.getSessionInternal(Request.java:2521)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:429)
	at tomcat.request.session.redis.SessionHandlerValve.invoke(SessionHandlerValve.java:37)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

But, the object seems ok in redis.
Can you help me?

Thanks in advance.
